from __future__ import annotations

from typing import Any

from ocppscan.checks.base import CheckResult, Status


_SEVERITY_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "HIGH": "🟠 HIGH",
    "MEDIUM": "🟡 MEDIUM",
    "LOW": "🔵 LOW",
    "INFO": "⚪ INFO",
}

_STATUS_BADGE = {
    "PASS": "✅ PASS",
    "FAIL": "❌ FAIL",
    "ERROR": "⚠️ ERROR",
    "SKIP": "⏭️ SKIP",
    "INCONCLUSIVE": "❓ INCONCLUSIVE",
}


def render_markdown(meta: dict[str, Any], results: list[CheckResult]) -> str:
    lines: list[str] = []

    lines.append("# OCPPScan Security Assessment Report")
    lines.append("")
    lines.append(f"**Target:** `{meta.get('target', 'unknown')}`  ")
    lines.append(f"**Charger ID:** `{meta.get('charger_id', 'unknown')}`  ")
    lines.append(f"**Protocol:** OCPP {meta.get('version', 'unknown')}  ")
    lines.append(f"**Timestamp:** {meta.get('timestamp', 'unknown')}  ")
    lines.append("")
    lines.append("> This report was generated by OCPPScan. Only run against systems you own or have written authorisation to test.")
    lines.append("")

    failures = [r for r in results if r.status == Status.FAIL]
    severities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    counts = {s: sum(1 for r in failures if r.severity.value == s) for s in severities}
    overall = next((s for s in severities if counts[s] > 0), "PASS")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"**Overall Risk:** {_SEVERITY_BADGE.get(overall, overall) if overall != 'PASS' else '✅ PASS — No findings'}")
    lines.append("")
    lines.append("| Severity | Findings |")
    lines.append("|----------|----------|")
    for sev in severities:
        lines.append(f"| {_SEVERITY_BADGE[sev]} | {counts[sev]} |")
    lines.append("")
    lines.append(f"**Checks run:** {len(results)}  ")
    lines.append(f"**Findings (FAIL):** {len(failures)}  ")
    lines.append("")

    lines.append("## Check Results")
    lines.append("")
    lines.append("| Check ID | Severity | Status | Name |")
    lines.append("|----------|----------|--------|------|")
    for r in results:
        lines.append(
            f"| `{r.id}` | {_SEVERITY_BADGE.get(r.severity.value, r.severity.value)} "
            f"| {_STATUS_BADGE.get(r.status.value, r.status.value)} | {r.name} |"
        )
    lines.append("")

    if failures:
        lines.append("## Findings")
        lines.append("")
        for r in failures:
            lines.append(f"### {_SEVERITY_BADGE.get(r.severity.value, r.severity.value)} — {r.name}")
            lines.append("")
            lines.append(f"**Check ID:** `{r.id}`")
            lines.append("")
            lines.append(f"**Description:** {r.description}")
            lines.append("")
            if r.evidence:
                lines.append("**Evidence:**")
                lines.append("```json")
                import json
                lines.append(json.dumps(r.evidence, indent=2))
                lines.append("```")
                lines.append("")
            if r.remediation:
                lines.append(f"**Remediation:** {r.remediation}")
                lines.append("")
            if r.references:
                lines.append("**References:**")
                for ref in r.references:
                    lines.append(f"- {ref}")
                lines.append("")
            lines.append("---")
            lines.append("")

    return "\n".join(lines)
